---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.1.3
resources:
  - name: m2
    type: docker-image
    source:
      repository: making/home-m2
      username: {{docker-username}}
      password: {{docker-password}}  
      email: {{docker-email}}  
  - name: home-repo
    type: git
    source:
      uri: https://github.com/maki-home/home-services
      branch: master
  - name: utils
    type: git
    source:
      uri: https://github.com/maki-home/concourse-utils
      branch: master
  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook-url}}
jobs:
  - name: init-m2
    plan:
      - aggregate:
        - get: home-repo
        - get: utils
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: home-repo
              path: repo
            - name: utils
          outputs:
            - name: to-push  
          run:
            path: sh 
            args: 
            - -c
            - |
              repo/ci/tasks/m2.sh init
      - put: m2
        params:
          import_file: to-push/rootfs.tar
        on_success:
          put: slack-alert
          params:
            channel: '#concourse'
            text: |
              <!here> :white_check_mark: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* succeeded with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!
        on_failure:
          put: slack-alert
          params:
            channel: '#concourse'
            text: |
              <!here> :rotating_light: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* failed with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!
  - name: update-m2
    plan:
      - aggregate:
        - get: home-repo
        - get: utils
        - get: m2
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: home-repo
              path: repo
            - name: utils
            - name: m2
          outputs:
            - name: to-push    
          run:
            path: sh
            args:
            - -c
            - |
              repo/ci/tasks/m2.sh
      - put: m2
        params:
          import_file: to-push/rootfs.tar
        on_success:
          put: slack-alert
          params:
            channel: '#concourse'
            text: |
              <!here> :white_check_mark: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* succeeded with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!
        on_failure:
          put: slack-alert
          params:
            channel: '#concourse'
            text: |
              <!here> :rotating_light: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* failed with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!